# Generated by Django 6.0.2 on 2026-04-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('A', 'Season A (Sep–Feb)'), ('B', 'Season B (Mar–Jul)')], max_length=2)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('predicted_price', models.FloatField(help_text='RWF per kg')),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Huye', 'Huye'), ('Musanze', 'Musanze'), ('Karongi', 'Karongi'), ('Kirehe', 'Kirehe'), ('Kigali', 'Kigali'), ('Nyagatare', 'Nyagatare'), ('Rubavu', 'Rubavu')], max_length=100)),
                ('seed_type', models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Irish Potato', 'Irish Potato'), ('Wheat', 'Wheat'), ('Sorghum', 'Sorghum'), ('Rice', 'Rice')], max_length=100)),
                ('land_size', models.FloatField(help_text='In hectares')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
